{-# LANGUAGE OverloadedStrings #-}

-- | OpenAPI Specification
--
-- Serves OpenAPI 3.0 specification for the BPC API.
--
-- @since 0.1.0.0
module BPC.API.OpenAPI
  ( openApiHandler
  , openApiSpec
  ) where

import Data.Text (Text)
import qualified Data.Text as T

import BPC.API.App (AppM)

-- | OpenAPI handler.
--
-- GET /docs/openapi.yaml
-- Returns OpenAPI 3.0 specification.
--
-- @since 0.1.0.0
openApiHandler :: AppM Text
openApiHandler = pure openApiSpec

-- | OpenAPI specification (YAML).
openApiSpec :: Text
openApiSpec = T.unlines
  [ "openapi: 3.0.3"
  , "info:"
  , "  title: Battery Passport Compiler API"
  , "  version: 0.1.0"
  , "  description: |"
  , "    RESTful API for the Battery Passport Compiler."
  , "    Provides endpoints for document management, snapshot creation,"
  , "    passport compilation, and audit trail verification."
  , "  contact:"
  , "    email: team@bpc.example"
  , ""
  , "servers:"
  , "  - url: http://localhost:8080"
  , "    description: Development server"
  , ""
  , "security:"
  , "  - bearerAuth: []"
  , ""
  , "components:"
  , "  securitySchemes:"
  , "    bearerAuth:"
  , "      type: http"
  , "      scheme: bearer"
  , "      bearerFormat: API Key"
  , ""
  , "  schemas:"
  , "    Error:"
  , "      type: object"
  , "      properties:"
  , "        error:"
  , "          type: object"
  , "          properties:"
  , "            code:"
  , "              type: string"
  , "            message:"
  , "              type: string"
  , "            correlation_id:"
  , "              type: string"
  , "              format: uuid"
  , ""
  , "    Document:"
  , "      type: object"
  , "      properties:"
  , "        id:"
  , "          type: string"
  , "          format: uuid"
  , "        name:"
  , "          type: string"
  , "        mime_type:"
  , "          type: string"
  , "        created_at:"
  , "          type: string"
  , "          format: date-time"
  , ""
  , "    Snapshot:"
  , "      type: object"
  , "      properties:"
  , "        id:"
  , "          type: string"
  , "          format: uuid"
  , "        status:"
  , "          type: string"
  , "          enum: [BUILDING, READY, SEALED]"
  , "        hash:"
  , "          type: string"
  , "          nullable: true"
  , ""
  , "    Passport:"
  , "      type: object"
  , "      properties:"
  , "        id:"
  , "          type: string"
  , "          format: uuid"
  , "        battery_product_id:"
  , "          type: string"
  , "          format: uuid"
  , ""
  , "paths:"
  , "  /health/live:"
  , "    get:"
  , "      summary: Liveness probe"
  , "      security: []"
  , "      responses:"
  , "        '200':"
  , "          description: Server is alive"
  , ""
  , "  /health/ready:"
  , "    get:"
  , "      summary: Readiness probe"
  , "      security: []"
  , "      responses:"
  , "        '200':"
  , "          description: Server is ready"
  , "        '503':"
  , "          description: Server is not ready"
  , ""
  , "  /v1/documents:"
  , "    post:"
  , "      summary: Create document"
  , "      requestBody:"
  , "        required: true"
  , "        content:"
  , "          application/json:"
  , "            schema:"
  , "              type: object"
  , "              properties:"
  , "                name:"
  , "                  type: string"
  , "                mime_type:"
  , "                  type: string"
  , "      responses:"
  , "        '201':"
  , "          description: Document created"
  , "    get:"
  , "      summary: List documents"
  , "      parameters:"
  , "        - name: limit"
  , "          in: query"
  , "          schema:"
  , "            type: integer"
  , "            default: 20"
  , "        - name: cursor"
  , "          in: query"
  , "          schema:"
  , "            type: string"
  , "      responses:"
  , "        '200':"
  , "          description: Document list"
  , ""
  , "  /v1/snapshots:"
  , "    post:"
  , "      summary: Create snapshot"
  , "      responses:"
  , "        '201':"
  , "          description: Snapshot created"
  , "    get:"
  , "      summary: List snapshots"
  , "      responses:"
  , "        '200':"
  , "          description: Snapshot list"
  , ""
  , "  /v1/passports:"
  , "    post:"
  , "      summary: Create passport"
  , "      responses:"
  , "        '201':"
  , "          description: Passport created"
  , "    get:"
  , "      summary: List passports"
  , "      responses:"
  , "        '200':"
  , "          description: Passport list"
  ]
