FROM haskell:9.6.4 as build
WORKDIR /src
COPY . .
RUN cabal update && cabal build bpc-cli:exe:bpc-cli

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libpq5 ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /src/dist-newstyle/ /app/dist-newstyle/
CMD ["/app/dist-newstyle/build/x86_64-linux/ghc-9.6.4/bpc-cli-0.1.0.0/x/bpc-cli/build/bpc-cli/bpc-cli"]
